routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReservoirController;
use \App\Http\Controllers\ForumController;
use App\Http\Controllers\FishController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::any('/reservoir/saveCoordinates', [ReservoirController::class, 'saveCoordinates']);
Route::any('/reservoir/{reservoirId}/update', [ReservoirController::class, 'update']);
Route::get('/reservoir/getCoordinates', [ReservoirController::class, 'getCoordinates']);
Route::get('/reservoir/showCoordinates', [ReservoirController::class, 'showCoordinates'])->name('show');
Route::get('/reservoir/showUnacceptedCoordinates', [ReservoirController::class, 'showUnacceptedCoordinates'])->name('unaccepted');
Route::any('/reservoir/{reservoirId}/acceptCoordinates', [ReservoirController::class, 'acceptCoordinates'])->name('acceptCoordinates');
Route::get('/reservoir/{reservoirId}/getCoordinateEdit', [ReservoirController::class, 'getCoordinateEdit']);
Route::get('/reservoir/{reservoirId}/showSingleReservoir', [ReservoirController::class, 'showSingleReservoir']);
Route::get('/forum/{forumId}/getComments', [ForumController::class, 'getComments']);
Route::any('/forum/{forumId}/update', [ForumController::class, 'update'])->name('updateForum');
Route::any('/fish/storeFish', [FishController::class, 'storeFish']);
Route::any('/comment/store', [CommentController::class, 'store']);
Route::any('/fish/{fishId}/update', [FishController::class, 'update']);

Route::resource('reservoir', 'App\Http\Controllers\ReservoirController');
Route::resource('forum', 'App\Http\Controllers\ForumController');
Route::resource('comment', CommentController::class);
Route::resource('fish', FishController::class);

Auth::routes();
Route::any('/profile',[ProfileController::class, 'index'])->name('profile');
Route::any('/profile/getEmails',[ProfileController::class, 'getEmails'])->name('getEmails');

Route::any('/uploadImage',[ProfileController::class, 'addImage'])->name('uploadImage');
Route::any('/changePassword',[ProfileController::class, 'changePassword'])->name('changePassword');
Route::post('/saveNewPassword',[ProfileController::class, 'saveNewPassword'])->name('saveNewPassword');
Route::any('/editProfile',[ProfileController::class, 'editProfile'])->name('editProfile');
Route::any('/saveEditProfile',[ProfileController::class, 'saveEditProfile'])->name('saveEditProfile');

Route::get('/', function () {return view('welcome');})->name('home');

app/Models/Fish.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fish extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'image',
        'link'
    ];

    protected $primaryKey = 'id';
}

app/Http/Controllers/FishController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fish;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;

class FishController extends Controller
{
    const ADMIN = 'administrator';

    /**
     * Display a listing of fish resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fishes = Fish::all();
        return view('fish.index', compact('fishes'));
    }

    /**
     * Show the form for creating a new fish species.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) { //checking if user is admin
                return view('fish.create');
            }
        }

        return redirect()->route('fish.index')->with('error', 'Zivs sugu var pievienot tikai administrators!');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//
    }

    /**
     * Store a newly created fish specie in database.
     *
     * @param Request $request
     */
    public function storeFish(Request $request) {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        $imageName = time().'.'.$request->image->extension(); //renaming to unique
        $request->image->move(public_path('images/fishes'), $imageName); //saving to pub folder

        $fish = array(
            'name' => $request->name,
            'link' => $request->link,
            'image' => $imageName
        );

        Fish::create($fish); //creating fish specie
    }

    /**
     * Display the specified fish specie.
     *
     * @param  \App\Models\Fish  $fish
     * @return \Illuminate\Http\Response
     */
    public function show(Fish $fish)
    {
        if (!Fish::find($fish->id)) {
            return redirect()->route('fish.index')->with('error', 'Zivs suga ar doto identifikatoru neeksistē datubāzē!');
        }

        return view('fish.show', compact('fish'));
    }

    /**
     * Show the form for editing the specified fish specie.
     *
     * @param  \App\Models\Fish  $fish
     * @return \Illuminate\Http\Response
     */
    public function edit(Fish $fish)
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) { //checking if admin
                return view('fish.edit', compact('fish'));
            }
        }

        return redirect()->route('fish.index')->with('error', 'Zivs sugu var rediģēt tikai administrators!');
    }

    /**
     * Update the specified fish specie in database.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Fish  $fish
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Fish $fish)
    {
        $imageName = null;
        if($request->isImageChanged == 'true') {
            $request->validate([
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);
            $imageName = time().'.'.$request->image->extension(); //renaming to unique
            $request->image->move(public_path('images/fishes'), $imageName); //moving to public forlder
            $image_path = sprintf('%s/images/fishes/%s', public_path(), $fish->image);
            if(File::exists($image_path)) { //deleting previously saved image
                File::delete($image_path);
            }
        }

        $fish_update = array(
            'name' => $request->name,
            'link' => $request->link,
            'image' => $imageName ? $imageName : $fish->image
        );

        $fish->update($fish_update); //updating specie
    }


    /**
     * Deleting the specified fish specie in database.
     *
     * @param Fish $fish
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Fish $fish): \Illuminate\Http\RedirectResponse
    {
        if (!Fish::find($fish->id)) {
            return redirect()->route('fish.index')->with('error', 'Zivs suga ar doto identifikatoru neeksistē datubāzē!');
        }

        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) {
                DB::table('fish_reservoir')->where('fish_id', $fish->id)->delete(); //removing fish from reservoir
                $image_path = sprintf('%s/images/fishes/%s', public_path(), $fish->image);
                if(File::exists($image_path)) { //deleting fish image
                    File::delete($image_path);
                }
                $fish->delete(); //deleting fish specie

                return redirect()->route('fish.index')
                    ->with('success','Zivs suga tika izdzēsta!');

            }
        }

        return redirect()->route('fish.index')->with('error', 'Zivs sugu var izdzēst tikai administrators!');
    }
}

resources/views/fish/create.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
        @csrf
        <h3>Zivs pievienošana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="name" name="name" required minlength="4">
        </div>
        <div class="form-group">
            <label>Links</label>
            <input class="form-control" type="text" id="link" name="link" required>
        </div>
        <div class="ImageUploader">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <label>Bilde</label>
                    <input type="file" name="image" id="uploaded-image" class="form-control">
                </div>
            </div>
        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0" id="save-fish" type="submit">Pievienot</button>
    </div>
    <script src="{{ asset('js/fish/uploader.js')  }}"></script>
@endsection
    <b></b>

resources/views/fish/edit.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
        @csrf
        <h3>Zivs rediģēšana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="name" name="name" required minlength="4" value="{{ $fish->name }}">
        </div>
        <div class="form-group">
            <label>Links</label>
            <input class="form-control" type="text" id="link" name="link" required value="{{ $fish->link }}">
        </div>
        <div class="form-group" id="change">
            <img src="{{ asset(sprintf('/images/fishes/%s', $fish->image))  }}" style="width: 400px; height: 200px; margin: auto" alt="fish image">
            <button class="btn btn-info" id="change-image">Mainīt bildi</button>
        </div>
        <div class="ImageUploader" id="ImageUploader" style="display: none;">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <label>Bilde</label>
                    <input type="file" name="image" id="uploaded-image" class="form-control">
                </div>
            </div>
        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0" id="save-fish" type="submit">Saglabāt</button>
    </div>
    <script src="{{ asset('js/fish/edit.js')  }}"></script>
@endsection
<b></b>

resources/views/fish/index.blade.php
@extends('layout.mainlayout')
@section('content')
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Zivs</th>
            <th scope="col">Bilde</th>
            <th scope="col">Izveidots</th>
            <th scope="col">Atjaunots</th>
            <th scope="col">Opcijas</th>
        </tr>
        </thead>
        <tbody>
        @foreach($fishes as $fish)
            <tr>
                <td>{{ $fish->name }}</td>
                <td><img src="{{ asset(sprintf('/images/fishes/%s',$fish->image))  }}" style="height: 100px; width: 200px;" alt="fish image"></td>
                <td>{{ $fish->created_at }}</td>
                <td>{{ $fish->updated_at }}</td>
                <td>
                    <form action="{{ route('fish.destroy',$fish->id) }}" method="POST">
                        <a href="{{ sprintf('%s/%s', \Illuminate\Support\Facades\URL::to('/fish'), $fish->id)  }}" class="btn btn-success">Apskatīt</a>
                        @auth()
                            @if(Auth::user()->role == 'administrator')
                                <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/fish'), $fish->id,'edit')  }}" class="btn btn-info">Rediģēt</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Dzēst</button>
                            @endif
                        @endauth
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection
<b></b>

resources/views/fish/show.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
        @csrf
        <h3>{{ $fish->name }}</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="name" name="name" readonly minlength="4" value="{{ $fish->name }}">
        </div>
        <div class="form-group">
            <a href="{{ $fish->link  }}" target="_blank">Vairāk informācijas</a>
        </div>
        <div class="form-group" id="change">
            <img src="{{ asset(sprintf('/images/fishes/%s', $fish->image))  }}" style="width: 400px; height: 200px; margin: auto" alt="fish image">
        </div>
    </div>
@endsection
<b></b>