routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReservoirController;
use \App\Http\Controllers\ForumController;
use App\Http\Controllers\FishController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::any('/reservoir/saveCoordinates', [ReservoirController::class, 'saveCoordinates']);
Route::any('/reservoir/{reservoirId}/update', [ReservoirController::class, 'update']);
Route::get('/reservoir/getCoordinates', [ReservoirController::class, 'getCoordinates']);
Route::get('/reservoir/showCoordinates', [ReservoirController::class, 'showCoordinates'])->name('show');
Route::get('/reservoir/showUnacceptedCoordinates', [ReservoirController::class, 'showUnacceptedCoordinates'])->name('unaccepted');
Route::any('/reservoir/{reservoirId}/acceptCoordinates', [ReservoirController::class, 'acceptCoordinates'])->name('acceptCoordinates');
Route::get('/reservoir/{reservoirId}/getCoordinateEdit', [ReservoirController::class, 'getCoordinateEdit']);
Route::get('/reservoir/{reservoirId}/showSingleReservoir', [ReservoirController::class, 'showSingleReservoir']);
Route::get('/forum/{forumId}/getComments', [ForumController::class, 'getComments']);
Route::any('/forum/{forumId}/update', [ForumController::class, 'update'])->name('updateForum');
Route::any('/fish/storeFish', [FishController::class, 'storeFish']);
Route::any('/comment/store', [CommentController::class, 'store']);
Route::any('/fish/{fishId}/update', [FishController::class, 'update']);

Route::resource('reservoir', 'App\Http\Controllers\ReservoirController');
Route::resource('forum', 'App\Http\Controllers\ForumController');
Route::resource('comment', CommentController::class);
Route::resource('fish', FishController::class);

Auth::routes();
Route::any('/profile',[ProfileController::class, 'index'])->name('profile');
Route::any('/profile/getEmails',[ProfileController::class, 'getEmails'])->name('getEmails');

Route::any('/uploadImage',[ProfileController::class, 'addImage'])->name('uploadImage');
Route::any('/changePassword',[ProfileController::class, 'changePassword'])->name('changePassword');
Route::post('/saveNewPassword',[ProfileController::class, 'saveNewPassword'])->name('saveNewPassword');
Route::any('/editProfile',[ProfileController::class, 'editProfile'])->name('editProfile');
Route::any('/saveEditProfile',[ProfileController::class, 'saveEditProfile'])->name('saveEditProfile');

Route::get('/', function () {return view('welcome');})->name('home');

app/Models/Forum.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Forum extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'desc',
        'reservoir_id',
    ];

    protected $primaryKey = 'id';
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Fish;
use App\Models\Forum;
use App\Models\Reservoir;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ForumController extends Controller
{
    const ADMIN = 'administrator';

    /**
     * Display a listing of the forums.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forums = Forum::all();
        return view('forum.index', compact('forums'));
    }

    /**
     * Show the form for creating a new forum.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) {
                $possibleForms = $this->getFutureForms(); //getting list of reservoirs, that don't have forums yet
                return view('forum.create', compact('possibleForms'));
            }
        }

        return redirect()->route('forum.index')->with('error', 'Forumu var pievienot tikai administrators!');
    }

    /**
     * Returning all reservoirs, that haven't had any forum attached
     *
     * @return array
     */
    public function getFutureForms() {
        $reservoirs = Reservoir::all()->where('status', true);
        $futureForms = [];

        foreach ($reservoirs as $reservoir) {
            if(!$this->hasForum($reservoir)) {
                array_push($futureForms, $reservoir);
            }
        }

        return $futureForms;
    }

    /**
     * Checks if reservoir has forum or not
     *
     * @param $reservoir
     * @return bool
     */
    public function hasForum($reservoir): bool
    {
        if (DB::table('forums')->where('reservoir_id', $reservoir->id)->count() > 0) {
           return true;
        }

        return false;
    }

    /**
     * Sends to frontend all comment and user data via Ajax call
     *
     * @param $reservoirId
     * @return array
     */
    public function getComments($reservoirId) {
        $forumId = Forum::where('reservoir_id', $reservoirId)->get()->first()->id;

        try {
            $data = [
              'comments' => Comment::where('forum_id', $forumId)->get(),
              'user_data' => User::all('id', 'name'),
              'curr_user' => Auth::guest() ? null : Auth::id() //checks if user is signed
            ];
            json_encode($data);
        }
        catch (\mysql_xdevapi\Exception $exception) {
            $data = [
                'status' => 'error',
                'message' => $exception
            ];
            $data->toJson();
        }
        return $data;
    }


    /**
     * Storing form data
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request): \Illuminate\Http\RedirectResponse
    {
        $message = $this->validation($request->title, $request->desc, $request->reservoir);
       if (empty($message)) {
           $forum = [
               'title' => $request->title,
               'desc' => $request->desc,
               'reservoir_id' => $request->reservoir
           ];

           Forum::create($forum);
           return redirect()->route('forum.index')
               ->with('success', 'Diskusija tika pievienota veiksmīgi!');
       }

        return redirect()->route('forum.create')->with('error-array',$message)->withInput($request->all());
    }

    /**
     * Validating forum data
     *
     * @param $title
     * @param $desc
     * @param $reservoirId
     * @return array
     */
    public function validation($title, $desc, $reservoirId)
    {
        $message = [];

        if (strlen($title) < 8 || !preg_match('/^[a-žA-Ž\s]+$/', $title)) { //using regex to check if consists of only letters
            array_push($message, 'Diskusijas nosaukums ir mazāks par 8 burtiem vai satur simbolus, kas nav latīniski burti.');
        }

        if (strlen($desc) < 40) {
            array_push($message, 'Diskusijas apraksts satur mazāk par 40 simboliem.');
        }

        if(!Reservoir::find($reservoirId)) {
            array_push($message, 'Pievienotā ūdenstilpne neeksistē datubāzē.');
        }

        return $message;
    }


    /**
     * Returning specific forum view with fishes, comments are got by another function and displayed with JS
     *
     * @param $forum
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($forum)
    {
        $reservoirForum = Forum::where('reservoir_id', $forum)->get()->first();

        if (!empty($reservoirForum)) {
            $fishesIDs = DB::table('fish_reservoir')->where('reservoir_id', $forum)->get()->all();
            $fishes = [];
            foreach ($fishesIDs as $fish) {
                array_push($fishes, Fish::find($fish->fish_id));
            }
            return view('forum.show', compact('reservoirForum', 'fishes'));
        }

        return redirect()->route('forum.index')->with('error','Diskusija ar doto ID neeksistē datubāzē.');
    }


    /**
     * Returns forum edit view with reservoirs that doesn't have form yet
     *
     * @param Forum $forum
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Forum $forum)
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) { //checks if admin
                $possibleForms = $this->getFutureForms();
                return view('forum.edit', compact('forum', 'possibleForms'));
            }
        }

        return redirect()->route('forum.index')->with('error', 'Forumu var rediģēt tikai administrators!');
    }


    /**
     * Updating forum data
     *
     * @param Request $request
     * @param $forumId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $forumId)
    {
        $message = $this->validation($request->title, $request->desc, $request->reservoir_id);
        if (empty($message)) {
            $forum = Forum::find($forumId);
            $forum->update($request->all());

            return redirect()->route('forum.edit', $forum->id)
                ->with('success', 'Diskusija ir atjaunota veiksmīgi');
        }

        return redirect()->route('forum.edit', $forumId)->with('error-array',$message);

    }


    /**
     * Deleting forum data
     *
     * @param $forumId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($forumId)
    {
        if (empty(Forum::find($forumId))) {
            return redirect()->route('forum.index')->with('error', 'Diskusija ar doto ID neeksistē.');
        }

        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) { //checks if admin
                DB::table('comments')->where('forum_id', $forumId)->delete(); //deleting all comments that were attached to forum
                $forum = Forum::find($forumId);
                $forum->delete();
                return redirect()->route('forum.index')
                    ->with('success', 'Diskusija ir izdzēsta veiksmīgi');
            }
        }

        return redirect()->route('forum.index')->with('error', 'Forumu var izdzēst tikai administrators!');
    }
}

resources/views/forum/create.blade.php
@extends('layout.mainlayout')
@section('content')
    <form class="form-container" method="POST" action="{{  route('forum.store') }}">
        @csrf
        <h3>Diskusijas pievienošana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="title" name="title"  value="{{ old('title') }}">
        </div>
        <div class="form-group">
            <label>Apraksts</label>
            <textarea class="form-control" type="text" id="desc" name="desc" >{{ old('desc') }}</textarea>
        </div>
        <div class="form-group">
            <label>Ūdenstilpne</label>
            <select class="type-select" name="reservoir" id="reservoir" required>
              @if($possibleForms != [])
                  @foreach($possibleForms as $reservoir)
                     <option value="{{ $reservoir->id }}" {{ $reservoir->id == old('reservoir') ? 'selected="selected"' :''  }}>
                         {{ $reservoir->name  }}
                     </option>
                   @endforeach
              @endif
            </select>
        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0" id="save-reservoir" type="submit">Pievienot</button>
@endsection
<b></b>

resources/views/forum/edit.blade.php
@extends('layout.mainlayout')
@section('content')
    <form class="form-container" method="post" action="{{  route('updateForum', $forum->id) }}">
        @csrf
        <h3>Diskusijas rediģēšana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="title" name="title"  value="{{ $forum->title  }}">
        </div>
        <div class="form-group">
            <label>Apraksts</label>
            <textarea class="form-control" type="text" id="desc" name="desc" > {{ $forum->desc }} </textarea>
        </div>
        <div class="form-group">
            <label>Ūdenstilpne</label>
            <select class="type-select" name="reservoir_id" id="reservoir_id" required>
                <option value="{{ $forum->reservoir_id  }}">
                    {{ \Illuminate\Support\Facades\DB::table('reservoirs')->where('id',  $forum->reservoir_id)->first()->name  }}
                </option>
                @if($possibleForms != [])
                    @foreach($possibleForms as $reservoir)
                        <option value="{{ $reservoir->id }}">
                            {{ $reservoir->name  }}
                        </option>
                    @endforeach
                @endif
            </select>
        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0" id="save-reservoir" type="submit">Atjaunot</button>
        @endsection
        <b></b>

resources/views/forum/index.blade.php
@extends('layout.mainlayout')
@section('content')
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Forums</th>
            <th scope="col">Izveidots</th>
            <th scope="col">Atjaunots</th>
            <th scope="col">Opcijas</th>
        </tr>
        </thead>
        <tbody>
        @foreach($forums as $forum)
            <tr>
                <td>{{ $forum->title }}</td>
                <td>{{ $forum->created_at }}</td>
                <td>{{ $forum->updated_at }}</td>
                <td>
                    <form action="{{ route('forum.destroy',$forum->id) }}" method="POST">
                        <a href="{{ sprintf('%s/%s', \Illuminate\Support\Facades\URL::to('/forum'), $forum->reservoir_id)  }}" class="btn btn-success">Apskatīt</a>
                        @auth
                            @if(Auth::user()->role == 'administrator')
                                <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/forum'), $forum->id,'edit')  }}" class="btn btn-info">Rediģēt</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Dzēst</button>
                            @endif
                        @endauth
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection
<b></b>

resources/views/forum/show.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="container-fluid mt-100">
        <div class="row forum">
            <div class="col-md-12 forum-header">
                <div class="card mb-4">
                    <div class="card-header">
                       <h1 class="reservoir-header">{{ $reservoirForum->title }}</h1>
                    </div>
                    <div class="card-body">
                        {{ $reservoirForum->desc }}
                    </div>
                    <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                        <div class="fish-container" id="fish-container">
                            <button class="btn btn-success fish-button" id="show-more">Apskatīt zivis</button>
                            <ul class="fish-list" id="fish-list">
                                @foreach($fishes as $fish)
                                   <li class="fish row">
                                       <img class="mb-auto" src="{{ asset(sprintf('/images/fishes/%s', $fish->image))  }}" alt="fish image" style="width: 200px; height: 100px;">
                                       <a href="{{ sprintf('%s/fish/%s', \Illuminate\Support\Facades\URL::to('/'), $fish->id)  }}">{{ $fish->name }}</a>
                                   </li>
                                @endforeach
                            </ul>
                            <button class="btn btn-danger fish-button" id="show-less">Aizvērt</button>
                        </div>
                    </div>
                </div>
            </div>
            @auth
                <div class="comment-textarea">
                    <div class="alert alert-danger" id="comment-error"></div>
                    @csrf
                    <h3 class="comment-textarea-header">Pievienot komentāru:</h3>
                    <textarea name="comment-block" id="comment-block" cols="30" rows="10" class="form-control"></textarea>
                    <button id="publish-comment" class="btn-success btn">Publicēt</button>
                </div>
            @endauth
            <select class="mdb-select md-form btn btn-primary dropdown-toggle" id="order-selector">
                <option value="newest">Jaunākie -> vecākie</option>
                <option value="oldest">Vecākie -> Jaunākie</option>
            </select>
            <div id="comments" class="container"></div>
            <div class="forum-arrows">
                <div class="prev"><span class="icon"></span></div>
                <div id="pageCount"></div>
                <div class="next"><span class="icon"></span></div>
            </div>
        </div>
    </div>
    <script src="{{ asset('js/forum/comments.js')  }}"></script>
    <script src="{{ asset('js/forum/fish-listing.js')  }}"></script>
@endsection
<b></b>