routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReservoirController;
use \App\Http\Controllers\ForumController;
use App\Http\Controllers\FishController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::any('/reservoir/saveCoordinates', [ReservoirController::class, 'saveCoordinates']);
Route::any('/reservoir/{reservoirId}/update', [ReservoirController::class, 'update']);
Route::get('/reservoir/getCoordinates', [ReservoirController::class, 'getCoordinates']);
Route::get('/reservoir/showCoordinates', [ReservoirController::class, 'showCoordinates'])->name('show');
Route::get('/reservoir/showUnacceptedCoordinates', [ReservoirController::class, 'showUnacceptedCoordinates'])->name('unaccepted');
Route::any('/reservoir/{reservoirId}/acceptCoordinates', [ReservoirController::class, 'acceptCoordinates'])->name('acceptCoordinates');
Route::get('/reservoir/{reservoirId}/getCoordinateEdit', [ReservoirController::class, 'getCoordinateEdit']);
Route::get('/reservoir/{reservoirId}/showSingleReservoir', [ReservoirController::class, 'showSingleReservoir']);
Route::get('/forum/{forumId}/getComments', [ForumController::class, 'getComments']);
Route::any('/forum/{forumId}/update', [ForumController::class, 'update'])->name('updateForum');
Route::any('/fish/storeFish', [FishController::class, 'storeFish']);
Route::any('/comment/store', [CommentController::class, 'store']);
Route::any('/fish/{fishId}/update', [FishController::class, 'update']);

Route::resource('reservoir', 'App\Http\Controllers\ReservoirController');
Route::resource('forum', 'App\Http\Controllers\ForumController');
Route::resource('comment', CommentController::class);
Route::resource('fish', FishController::class);

Auth::routes();
Route::any('/profile',[ProfileController::class, 'index'])->name('profile');
Route::any('/profile/getEmails',[ProfileController::class, 'getEmails'])->name('getEmails');

Route::any('/uploadImage',[ProfileController::class, 'addImage'])->name('uploadImage');
Route::any('/changePassword',[ProfileController::class, 'changePassword'])->name('changePassword');
Route::post('/saveNewPassword',[ProfileController::class, 'saveNewPassword'])->name('saveNewPassword');
Route::any('/editProfile',[ProfileController::class, 'editProfile'])->name('editProfile');
Route::any('/saveEditProfile',[ProfileController::class, 'saveEditProfile'])->name('saveEditProfile');

Route::get('/', function () {return view('welcome');})->name('home');

app/Models/Reservoir.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reservoir extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'lat',
        'long',
        'type',
        'status'
    ];

    protected $primaryKey = 'id';

    public function fishes() //function that adds fishes to model
    {
        return $this->belongsToMany(Fish::class);
    }
}

app/Http/Controllers/ReservoirController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fish;
use App\Models\Reservoir;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ReservoirController extends Controller
{
    const ADMIN = 'administrator';

    /**
     * Return view of map with search functionality
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('reservoir.index');
    }


    /**
     * Returns view of reservoir creation
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function create()
    {
        $fishes = Fish::all(['id', 'name']);
        if (!Auth::guest()) {
            return view('reservoir.create', compact('fishes'));
        }

        return redirect()->route('home')->with('error', 'Tikai administrators var pievienot ūdenstilpni!');
    }


    /**
     * Returning view with list of accepted Reservoirs
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function showCoordinates()
    {
        $reservoirs = Reservoir::all()->where('status', true);
        return view('reservoir.show', compact('reservoirs'));
    }

    /**
     * Returning view with list of unaccepted Reservoirs
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function showUnacceptedCoordinates()
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) {
                $reservoirs = Reservoir::all()->where('status', false);
                return view('reservoir.unacceptedShow', compact('reservoirs'));
            }
        }

        return redirect()->route('home')->with('error', 'Tikai administrators var apskatīt neakceptētās ūdenstilpnes');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Saving reservoir to database
     *
     * @param Request $request
     */
    public function saveCoordinates(Request $request)
    {
        $reservoir = array(
            'name' => $request->name,
            'lat' => $request->lat,
            'long' => $request->long,
            'type' => $request->type,
            'status' => Auth::user()->role == self::ADMIN ? true : false
        );

        $reservoir = Reservoir::create($reservoir);
        $fishes = $request->fishes;
        foreach ($fishes as $fish) {
            $reservoir->fishes()->attach($fish);
        }
        $coordinates = json_decode($request->coordinates);

        foreach ($coordinates as $coordinate) {
            DB::table('coordinates')->insert(
                [
                    'reservoir_id' => $reservoir->id,
                    'lat' => $coordinate->lat,
                    'long' => $coordinate->lng,
                    'radius' => $request->radius
                ]
            );
        }
    }

    /**
     * Get all coordinates for specific reservoir and send them via Ajax to frontend
     *
     * @param Reservoir $reservoir
     * @return Reservoir[]|array|\Illuminate\Database\Eloquent\Collection
     */
    public function getCoordinateEdit($reservoir)
    {
        try {
            $data = DB::table('coordinates')->where('reservoir_id', $reservoir)->get();
            $data->toJson();
        }
        catch (\mysql_xdevapi\Exception $exception) {
            $data = [
                'status' => 'error',
                'message' => $exception
            ];
            $data->toJson();
        }
        return $data;
    }

    /**
     * Returns all coordinates in database to frontend
     *
     * @return array
     */
    public function getCoordinates()
    {
        try {
            $data = DB::table('coordinates')->get()->all();
            json_encode($data);
        }
        catch (\mysql_xdevapi\Exception $exception) {
            $data = [
                'status' => 'error',
                'message' => $exception
            ];
            $data->toJson();
        }
        return $data;
    }

    /**
     * Returning all accepted reservoir data to frontend
     *
     * @param Reservoir $reservoir
     * @return Reservoir[]|array|\Illuminate\Database\Eloquent\Collection
     */
    public function show()
    {
        try {
            $data = Reservoir::all()->where('status', true);
            $data->toJson();
        }
        catch (\mysql_xdevapi\Exception $exception) {
            $data = [
                'status' => 'error',
                'message' => $exception
            ];
            $data->toJson();
        }
        return $data;
    }

    /**
     * Show the form for editing the specified reservoir.
     *
     * @param  \App\Models\Reservoir  $reservoir
     * @return \Illuminate\Http\Response
     */
    public function edit(Reservoir $reservoir)
    {
        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) {
                $fishes = Fish::all(['id', 'name']);
                $coordinate = DB::table('coordinates')->where('reservoir_id', $reservoir->id)->first();
                $addedFishes = DB::table('fish_reservoir')->where('reservoir_id', $reservoir->id)->get();
                return view('reservoir.edit', compact('fishes', 'reservoir', 'coordinate', 'addedFishes'));
            }
        }

        return redirect()->route('home')->with('error', 'Tikai administrators var rediģēt ūdenstilpni!');
    }

    /**
     * Returning view of specific reservoir
     *
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function showSingleReservoir($id)
    {
        if (!Reservoir::find($id)) {
            return redirect()->route('home')->with('error', 'Ūdenstilpne neeksistē datubāzē.');
        }

        $fishes = Fish::all(['id', 'name']);
        $reservoir = Reservoir::find($id);
        $coordinate = DB::table('coordinates')->where('reservoir_id', $reservoir->id)->first();
        $addedFishes = DB::table('fish_reservoir')->where('reservoir_id', $reservoir->id)->get();

        return view('reservoir.single', compact('fishes', 'reservoir', 'coordinate', 'addedFishes'));
    }

    /**
     * Update the specified reservoir in database.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Reservoir  $reservoir
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $reservoir_update = array(
            'name' => $request->name,
            'lat' => $request->lat,
            'long' => $request->long,
            'type' => $request->type
        );
        $reservoir = Reservoir::find($id);
        $reservoir->update($reservoir_update);
        $fishes = $request->fishes;
        $this->removeDataBeforeUpdate($id); //removing all boundaries with other models before update

        foreach ($fishes as $fish) { //attaching new fish species
            $reservoir->fishes()->attach($fish);
        }

        $coordinates = json_decode($request->coordinates, true);

        foreach ($coordinates as $coordinate) { //attaching all new coordinates to reservoir
            DB::table('coordinates')->insert(
                [
                    'reservoir_id' => $reservoir->id,
                    'lat' => $coordinate['lat'],
                    'long' => isset($coordinate['long']) ? $coordinate['long'] : $coordinate['lng'] ,
                    'radius' => $request['radius']
                ]
            );
        }
    }

    /**
     * Allows admin to accept reservoir
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function acceptCoordinates($id)
    {
        if (Reservoir::find($id)) {
            return redirect()->route('home')->with('error', 'Datubāzē nav neakceptētās ūdenstilpnes dati.');
        }

        if (!Auth::guest()) {
            if (Auth::user()->role == self::ADMIN) { //checking if admin
                $reservoir = Reservoir::find($id);
                $reservoir->status = true;
                $reservoir->save();

                return redirect()->route('show')->with('success', 'Ūdenstilpne tika akceptēta!');
            }
        }

        return redirect()->route('home')->with('error', 'Ūdenstilpne var akceptēt tikai administrators!');
    }

    /**
     * Removing fishes and coordinates from reservoir before its edited
     *
     * @param $id
     */
    public function removeDataBeforeUpdate($id) {
        DB::table('fish_reservoir')->where('reservoir_id', $id)->delete();
        DB::table('coordinates')->where('reservoir_id', $id)->delete();
    }

    /**
     * Removing fishes, coordinates, forum and it's comments before reservoir is deleted
     *
     * @param $id
     */
    public function removeDataBeforeDelete($id)
    {
        DB::table('fish_reservoir')->where('reservoir_id', $id)->delete();
        DB::table('coordinates')->where('reservoir_id', $id)->delete();
        $forum =  DB::table('forums')->where('reservoir_id', $id);
        if(isset($forum)) {
            DB::table('comments')->where('forum_id', $forum->get()->first()->id)->delete();
            $forum->delete();
        }
    }


    /**
     * Deleting reservoir
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        if (!Reservoir::find($id)) {
            return redirect()->route('show')

resources/views/reservoir/create.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
            @csrf
            <h3>Ūdenstilpnes pievienošana</h3>
            <div class="form-group">
                <label>Nosaukums</label>
                <input class="form-control" type="text" id="name" name="name" required minlength="4">
            </div>
            <div class="form-group">
                <label>Platums</label>
                <input class="form-control" type="number" id="lat" step="any" name="lat" required>
            </div>
            <div class="form-group">
                <label>Garums</label>
                <input class="form-control"  type="number" id="long" step="any" name="long" required>
            </div>
            <div class="form-group">
                <label>Rādiuss (metros)</label>
                <input class="form-control" id="radius-select" type="number" name="radius" min="1" required>
            </div>
            <div id="createmap"></div>
            <div class="form-group">
                <label>Tips</label>
                <select class="type-select" name="type" id="type" required>
                    <option value="Ezers">Ezers</option>
                    <option value="Upe">Upe</option>
                </select>
            </div>
            <div class="form-group">
                <label>Zivis</label>
                <select id="fish-dropdown" name="fishes[]" multiple="multiple" class="form-control" >
                    @foreach($fishes as $fish)
                        <option value="{{ $fish->id }}">
                            {{ $fish->name }}
                        </option>
                    @endforeach
                </select>

            </div>
            <button class="btn btn-outline-primary my-2 my-sm-0" id="save-reservoir">Pievienot</button>
    </div>
    <script src="{{ asset('js/map/create-map.js')  }}"></script>
@endsection
<b></b>

resources/views/reservoir/edit.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
        @csrf
        <h3>Ūdenstilpnes rediģēšana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="name" name="name" required minlength="4" value="{{ $reservoir->name }}">
        </div>
        <div class="form-group">
            <label>Platums</label>
            <input class="form-control" type="number" id="lat" step="any" name="lat" required value="{{ $reservoir->lat }}">
        </div>
        <div class="form-group">
            <label>Garums</label>
            <input class="form-control"  type="number" id="long" step="any" name="long" required value="{{ $reservoir->long }}">
        </div>
        <div class="form-group">
            <label>Rādiuss (metros)</label>
            <input class="form-control" id="radius-select" type="number" name="radius" min="1" required value="{{ $coordinate->radius }}">
        </div>
        <div id="createmap"></div>
        <div class="form-group">
            <label>Tips</label>
            <select class="type-select" name="type" id="type" required value="{{ $reservoir->type }}">
                <option value="Ezers" {{ $reservoir->type == 'Ezers' ? 'selected' : '' }}>Ezers</option>
                <option value="Upe" {{ $reservoir->type == 'Upe' ? 'selected' : ''  }}>Upe</option>
            </select>
        </div>
        <div class="form-group">
            <label>Zivis</label>
            <select id="fish-dropdown" name="fishes[]" multiple="multiple" class="form-control" >
                @foreach($fishes as $fish)
                    <option value="{{ $fish->id }}" {{ isInList($addedFishes, $fish->id) ? 'selected' : '' }}>
                        {{ $fish->name }}
                    </option>
                @endforeach
            </select>

        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0" id="save-reservoir">Saglabāt izmaiņas</button>
    </div>
    <script src="{{ asset('js/map/edit-map.js')  }}"></script>
@endsection
<b></b>

resources/views/reservoir/index.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="album text-muted">
        <div class="container"  id="index-map">
            <div class="row">
                <div id="mapid"></div>
                <div class="search-content">
                    <input id="address-search"/>
                    <select class="type-select" name="type" id="type" required>
                        <option value="" disabled selected>Izvēlieties tipu</option>
                        <option value="Ezers">Ezers</option>
                        <option value="Upe">Upe</option>
                    </select>
                    <select class="mdb-select md-form" id="radius-selector">
                        <option value="" disabled selected>Izvēlieties meklēšanas radiusu</option>
                        <option value="25">~25 km</option>
                        <option value="50">~50 km</option>
                        <option value="100">~100 km</option>
                        <option value="All">Parādīt visus</option>
                    </select>
                    <button type="button" class="btn btn-success" id="searchButton">Meklēt</button>
                </div>
            </div>
        </div>
    </div>
@endsection
<b></b>

resources/views/reservoir/show.blade.php
@extends('layout.mainlayout')
@section('content')
    @if(!empty($reservoirs->all()))
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nosaukums</th>
                <th scope="col">Platums</th>
                <th scope="col">Garums</th>
                <th scope="col">Tips</th>
                <th scope="col">Izveidots</th>
                <th scope="col">Atjaunots</th>
                <th scope="col">Opcijas</th>
            </tr>
            </thead>
            <tbody>
            @foreach($reservoirs as $reservoir)
                <tr>
                    <td>{{ $reservoir->id }}</td>
                    <td>{{ $reservoir->name }}</td>
                    <td>{{ $reservoir->lat }}</td>
                    <td>{{ $reservoir->long }}</td>
                    <td>{{ $reservoir->type }}</td>
                    <td>{{ $reservoir->created_at }}</td>
                    <td>{{ $reservoir->updated_at }}</td>
                    <td>
                        <form action="{{ route('reservoir.destroy',$reservoir->id) }}" method="POST">
                            <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/reservoir'), $reservoir->id,'showSingleReservoir')  }}" class="btn btn-success">Apskatīt</a>
                            @auth
                                @if(Auth::user()->role == 'administrator')
                                    <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/reservoir'), $reservoir->id,'edit')  }}" class="btn btn-info">Rediģēt</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Dzēst</button>
                                @endif
                            @endauth
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-danger">Datubāzē nav ūdenstilpņu dati.</div>
    @endif
@endsection
<b></b>

resources/views/reservoir/single.blade.php
@extends('layout.mainlayout')
@section('content')
    <div class="form-container">
        @csrf
        <h3>Ūdenstilpnes apskatīšana</h3>
        <div class="form-group">
            <label>Nosaukums</label>
            <input class="form-control" type="text" id="name" name="name" readonly minlength="4" value="{{ $reservoir->name }}">
        </div>
        <div class="form-group">
            <label>Platums</label>
            <input class="form-control" type="number" id="lat" step="any" name="lat" readonly value="{{ $reservoir->lat }}">
        </div>
        <div class="form-group">
            <label>Garums</label>
            <input class="form-control"  type="number" id="long" step="any" name="long" readonly value="{{ $reservoir->long }}">
        </div>
        <div class="form-group">
            <label>Rādiuss (metros)</label>
            <input class="form-control" id="radius-select" type="number" name="radius" min="1" readonly value="{{ $coordinate->radius }}">
        </div>
        <div id="createmap"></div>
        <div class="form-group">
            <label>Tips</label>
            <select class="type-select" name="type" id="type" disabled value="{{ $reservoir->type }}">
                <option value="Ezers" {{ $reservoir->type == 'Ezers' ? 'selected' : '' }}>Ezers</option>
                <option value="Upe" {{ $reservoir->type == 'Upe' ? 'selected' : ''  }}>Upe</option>
            </select>
        </div>
        <div class="form-group">
            <label>Zivis</label>
            <select id="fish-dropdown" name="fishes[]" multiple="multiple" class="form-control" disabled >
                @foreach($fishes as $fish)
                    <option value="{{ $fish->id }}" {{ isInList($addedFishes, $fish->id) ? 'selected' : '' }}>
                        {{ $fish->name }}
                    </option>
                @endforeach
            </select>

        </div>
        @auth
            @if(Auth::user()->role == 'administrator' && $reservoir->status == false)
                <form method="post" action="{{ route('acceptCoordinates', $reservoir->id)  }}">
                    @csrf
                    <button class="btn btn-success" type="submit">Akceptēt</button>
                </form>
            @endif
        @endauth
    </div>
    <script src="{{ asset('js/map/single-map.js')  }}"></script>
@endsection
<b></b>

resources/views/reservoir/unacceptedShow.blade.php
@extends('layout.mainlayout')
@section('content')
    @if(!empty($reservoirs->all()))
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nosaukums</th>
                <th scope="col">Platums</th>
                <th scope="col">Garums</th>
                <th scope="col">Tips</th>
                <th scope="col">Izveidots</th>
                <th scope="col">Atjaunots</th>
                <th scope="col">Opcijas</th>
            </tr>
            </thead>
            <tbody>
            @foreach($reservoirs as $reservoir)
                <tr>
                    <td>{{ $reservoir->id }}</td>
                    <td>{{ $reservoir->name }}</td>
                    <td>{{ $reservoir->lat }}</td>
                    <td>{{ $reservoir->long }}</td>
                    <td>{{ $reservoir->type }}</td>
                    <td>{{ $reservoir->created_at }}</td>
                    <td>{{ $reservoir->updated_at }}</td>
                    <td>
                        <form action="{{ route('reservoir.destroy',$reservoir->id) }}" method="POST">
                            <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/reservoir'), $reservoir->id,'showSingleReservoir')  }}" class="btn btn-success">Apskatīt</a>
                            @auth
                                @if(Auth::user()->role == 'administrator')
                                    <a href="{{ sprintf('%s/%s/%s', \Illuminate\Support\Facades\URL::to('/reservoir'), $reservoir->id,'edit')  }}" class="btn btn-info">Rediģēt</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Dzēst</button>
                                @endif
                            @endauth
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-danger">Datubāzē nav ieteikto ūdenstilpņu dati.</div>
    @endif
@endsection
<b></b>