routes/web.php
<?php

use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReservoirController;
use \App\Http\Controllers\ForumController;
use App\Http\Controllers\FishController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::any('/reservoir/saveCoordinates', [ReservoirController::class, 'saveCoordinates']);
Route::any('/reservoir/{reservoirId}/update', [ReservoirController::class, 'update']);
Route::get('/reservoir/getCoordinates', [ReservoirController::class, 'getCoordinates']);
Route::get('/reservoir/showCoordinates', [ReservoirController::class, 'showCoordinates'])->name('show');
Route::get('/reservoir/showUnacceptedCoordinates', [ReservoirController::class, 'showUnacceptedCoordinates'])->name('unaccepted');
Route::any('/reservoir/{reservoirId}/acceptCoordinates', [ReservoirController::class, 'acceptCoordinates'])->name('acceptCoordinates');
Route::get('/reservoir/{reservoirId}/getCoordinateEdit', [ReservoirController::class, 'getCoordinateEdit']);
Route::get('/reservoir/{reservoirId}/showSingleReservoir', [ReservoirController::class, 'showSingleReservoir']);
Route::get('/forum/{forumId}/getComments', [ForumController::class, 'getComments']);
Route::any('/forum/{forumId}/update', [ForumController::class, 'update'])->name('updateForum');
Route::any('/fish/storeFish', [FishController::class, 'storeFish']);
Route::any('/comment/store', [CommentController::class, 'store']);
Route::any('/fish/{fishId}/update', [FishController::class, 'update']);

Route::resource('reservoir', 'App\Http\Controllers\ReservoirController');
Route::resource('forum', 'App\Http\Controllers\ForumController');
Route::resource('comment', CommentController::class);
Route::resource('fish', FishController::class);

Auth::routes();
Route::any('/profile',[ProfileController::class, 'index'])->name('profile');
Route::any('/profile/getEmails',[ProfileController::class, 'getEmails'])->name('getEmails');

Route::any('/uploadImage',[ProfileController::class, 'addImage'])->name('uploadImage');
Route::any('/changePassword',[ProfileController::class, 'changePassword'])->name('changePassword');
Route::post('/saveNewPassword',[ProfileController::class, 'saveNewPassword'])->name('saveNewPassword');
Route::any('/editProfile',[ProfileController::class, 'editProfile'])->name('editProfile');
Route::any('/saveEditProfile',[ProfileController::class, 'saveEditProfile'])->name('saveEditProfile');

Route::get('/', function () {return view('welcome');})->name('home');

resources/views/layout/partials/footer-scripts.blade.php
<!-- Bootstrap core JavaScript

================================================= -->

<!-- Placed at the end of the document so the pages load faster -->
<!-- Scripts -->
<script src="{{asset('js/vendor/app.js')}}" defer></script>
<script src="{{ asset('js/app.js') }}" defer></script>

resources/views/layout/partials/footer.blade.php
<footer class="text-muted">
    <div class="container">
        <p class="float-right hook">
            <span class="hook-img"></span>
        </p>
        <p>Makšķerēšanas klubs. Kursa darbs</p>
        <p>Autors: Latvijas Universitātes, Datorikas fakultātes students - Ričards Ņedosvitnijs</p>
    </div>
</footer>

resources/views/layout/partials/head.blade.php
<meta charset="utf-8">

<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Styles -->
<link href="{{ asset('css/leaflet.css') }}" rel="stylesheet">
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<meta name="csrf-token" content="{{ csrf_token() }}">

resources/views/layout/partials/header.blade.php
@if(session()->has('error'))
    <div class="alert alert-danger" style="max-width: 1440px; margin: auto">
        {{ session()->get('error')  }}
    </div>
@endif
@if(session()->has('error-array'))
    <div class="alert alert-danger" style="max-width: 1440px; margin: auto">
        @foreach(session()->get('error-array') as $error)
        {{ $error }} <br/>
        @endforeach
    </div>
@endif
@if(session()->has('success'))
    <div class="alert alert-success" style="max-width: 1440px; margin: auto">
        {{ session()->get('success')  }}
    </div>
@endif
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading" id="main-header">Makšķerēšanas klubs</h1>
    </div>
</section>
<div id="js-errors" class="alert-danger" style="max-width: 1440px; margin: auto; text-align: center;"></div>

resources/views/layout/partials/nav.blade.php
<div class="outer-nav">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Makšķērēšanas klubs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('reservoir.index') }}">Karte</a>
                </li>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdowns" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Ūdenstilpnes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdowns">
                        <a class="dropdown-item" href="{{ route('show')  }}">Saraksts</a>
                        @auth
                            @if(Auth::user()->role == 'administrator' || 'registered_user')
                                <a class="dropdown-item" href="{{ route('reservoir.create')  }}">Pievienot</a>
                            @endif
                            @if (Auth::user()->role == 'administrator')
                                    <a class="dropdown-item" href="{{ route('unaccepted')  }}">Neakceptētās ūdenstilpnes</a>
                            @endif
                        @endauth
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdowns" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Diskusijas
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdowns">
                        <a class="dropdown-item" href="{{ route('forum.index')  }}">Saraksts</a>
                        @auth
                            @if(Auth::user()->role == 'administrator')
                                <a class="dropdown-item" href="{{ route('forum.create')  }}">Pievienot</a>
                            @endif
                        @endauth
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdowns" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Zivis
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdowns">
                        <a class="dropdown-item" href="{{ route('fish.index')  }}">Saraksts</a>
                        @auth
                            @if(Auth::user()->role == 'administrator')
                                <a class="dropdown-item" href="{{ route('fish.create')  }}">Pievienot</a>
                            @endif
                        @endauth
                    </div>
                </div>
            </ul>
        </div>
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Ienākt') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Reģistrēties') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('profile') }}">
                            {{ __('Apskatīt profilu') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('editProfile') }}">
                            {{ __('Rediģēt profilu') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('changePassword') }}">
                            {{ __('Mainīt paroli') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Iziet') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </nav>
</div>